version: '3.8'

services:
  api:
    build: .
    container_name: uerjhub_backend
    ports:
      - "8000:8000"
    environment:
      # --- O ENDEREÇO CERTO É ESTE: ---
      - MONGO_URL=mongodb://mongo_db:27017 
    volumes:
      - ./backend/uploads:/app/backend/uploads
    depends_on:
      - mongo_db

  mongo_db:  # <--- Este é o nome que o backend usa para achar o banco
    image: mongo:latest
    container_name: uerjhub_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: